upgrade to 0.8.27
bcnmy/nexus pull request #159
Opened 2024-09-04 21:24 UTC by livingrockrises

2024-09-04 23:06 UTC, ankurdubey521 commented
Oh this is even better

2024-09-05 06:42 UTC, filmakarov requested changes

2024-09-05 06:42 UTC, filmakarov commented on foundry.toml
I suggest `via-ir = false` :)

Compiling 205 files with Solc 0.8.27

via-ir = false: Solc 0.8.27 finished in 22.65s
via-ir = true: Solc 0.8.27 finished in 177.23s

2024-09-05 07:56 UTC, livingrockrises commented on foundry.toml
where? I am setting env variable to false when I run

2024-09-05 07:58 UTC, livingrockrises commented on foundry.toml
ah missed in foundry.toml

2024-09-05 08:01 UTC, livingrockrises commented on foundry.toml
done

2024-09-05 08:54 UTC, ankurdubey521 approved these changes

2024-09-05 08:55 UTC, filmakarov approved these changes

2024-09-05 09:12 UTC, merged

2024-09-18 23:33 UTC, NoahMarconi commented on foundry.toml
> -  via-ir = true
might prefer profiles over globally turning off to allow for via-ir when deploying

2024-09-18 23:34 UTC, NoahMarconi commented on foundry.toml
> -  via-ir = true
although I see you have it in the hardhat to toggle on/off