Feat/sma 809 potential account factory (Draft)
bcnmy/nexus pull request #73
Opened 2024-05-16 10:33 UTC by livingrockrises

2024-05-16 11:37 UTC, livingrockrises commented
also linking this here
https://github.com/bcnmy/nexus/pull/74

2024-05-16 12:00 UTC, Aboudjem commented on contracts/utils/Bootstrap.sol
> +        BootstrapConfig[] calldata $valdiators,
typo

2024-05-16 12:00 UTC, Aboudjem commented on contracts/utils/Bootstrap.sol
> +     * Make sure that the MSA already initilazed the linked lists in the ModuleManager prior to
typo

2024-05-16 12:02 UTC, Aboudjem commented on contracts/common/Stakeable.sol
> +/**
can we use `///` there to keep consistency accross all the files

2024-05-16 12:04 UTC, Aboudjem commented on contracts/factory/BiconomyMetaFactory.sol
> +    // whitelist / blacklist a factory
add natspec

2024-05-16 12:04 UTC, Aboudjem commented on contracts/factory/BiconomyMetaFactory.sol
> +    // Note: deploy using only one of the whitelisted factories
same here

2024-05-16 12:05 UTC, Aboudjem commented on contracts/interfaces/common/IStakeable.sol
> +/**
///

2024-05-16 12:09 UTC, Aboudjem requested changes
It's not clear what are the differences between old and new factory, they have same functions.  could you highlight the main changes pls

2024-05-16 13:12 UTC, filmakarov commented
I agree to all the proposed changes. 
Ownable can help us managing stuff that will allow to mitigate HolterHus issue
having generic `bytes data` can also be useful. enabling several modules would be really useful

Question re MetaFactory
> it's address will be part of the initcode
can you elaborate on this please?

2024-05-16 13:17 UTC, livingrockrises commented
> I agree to all the proposed changes. Ownable can help us managing stuff that will allow to mitigate HolterHus issue having generic `bytes data` can also be useful. enabling several modules would be really useful
> 
> Question re MetaFactory
> 
> > it's address will be part of the initcode
> > can you elaborate on this please?

I made several functions in bootstrap contract for packing things to generic data
one is broad where you can enable n validators, n executors, hook and n fallbacks
I'm trying to think what would be used more often during deployment and what would be done post deployment by choice and less frequently.
so then I thought maybe n validators and 1 hook is enough? preparing data for this scoped init. wdyt?

> address will be part of the initcode
oh i mean this will be the actual factory recognised by initcode userop
initcode = address(meta factory) + selector(deployWithFactory)initData

but doing this both is possible to solve Holterhaus reported issue?
If I make generic data can you show how we would decode and check whitelist?

2024-05-16 16:23 UTC, livingrockrises commented
> > i mean this will be the actual factory recognised by initcode userop
> 
> I see. yeah, this is interesting. so this metafactory will be cosidered a factory by 4337. so it has to be staked.
> 
> > but doing this both is possible to solve Holterhaus reported issue? If I make generic data can you show how we would decode and check whitelist?
> 
> Can we move decoding and checking the wl/attestations to the factories that actually deploy the sa?

1. yes, it is stakeable. child factories can be just ownable

2. yes > decoding and checking the wl/attestations to the factories that actually deploy the sa

on this we have to decide which all kinds of factories we need,
a. one with K1 valdiator enshrined?
b. one with x modules just whitelisted. we will need to send large amount of data and decoding logic for these modules.
c. one with registry check on all modules

have to decide on wl vs registry
on previous call w rhinestone attestation flow is not super clear to me so I would refrain from that right away. 

wdyt?
what makes clear sense is meta factory and freedom to intro more factories and whitelist / enshrine / guard trail stuff inside them.
as long as format is clear say createAccount(bytes calldata initData, bytes32 salt)
and inside you're calling account.call(initData) vs perhaps account.initialise(initData) / account.initialise(_validators, _executors, _hook, _fallbacks)  

it would increase gas ofc but have to be reasonable in choices a bit.

2024-05-17 08:27 UTC, filmakarov commented
> wdyt? 

I think, with this meta factory concept, we can start with k1-factory and whitelist-factory. And wait until module registry flow is clearer.

2024-05-17 09:10 UTC, livingrockrises commented
> > wdyt?
> 
> I think, with this meta factory concept, we can start with k1-factory and whitelist-factory. And wait until module registry flow is clearer.

cool sounds good.
I will start making some changes

2024-05-17 16:54 UTC, livingrockrises commented
> > wdyt?
> 
> I think, with this meta factory concept, we can start with k1-factory and whitelist-factory. And wait until module registry flow is clearer.

in this case should I keep methods for all factories same createAccount(_data, _salt) or doing something like factory.call(packedwithfunctionselector) in meta factory?

2024-05-21 20:46 UTC, Aboudjem commented
Got some thoughts on the recent PR. I think we can simplify things and make it more efficient


1. Move the init logic into the NexusAccount directly this way we can get rid of `Bootstrap.sol` and `BootstrapUtil.sol`
2. enshrine whitelist of modules in the factory itself or maybe in the Meta (I'm not sure where will it be used here yet as it's used nowhere for the moment)
3. simplifying the initData structure by encoding everything within the NexusAccount reduces the need for decoding and number of  external calls

this will reduce gas with less external calls, simplify initData structure and reduce the number of contracts (files)

```
User
 |
 | Initiates account creation
 v
+----------------------+
| NexusMetaFactory     |
| - Verify Factory     |
+----------------------+
           |
           | deployWithFactory(factory, factoryData)
           v
+----------------------+
| Specific Factory     |
| - Verify Modules     |
| - Initialize Account |
+----------------------+
           |
           | createAccount(initData, salt)
           v
+----------------------+
| NexusAccount         |
| - Initialize Modules |
| - Configure Account  |
+----------------------+
           |
           | Initialization Complete
           v
         Account Created

```

Lmk what your thoughts

2024-05-24 16:30 UTC, livingrockrises commented
There are some review comments I am keeping and leaving a note here.

NexusAccountFactory
// Review may not need stakeable here


ModuleWhitelistFactory
// Review if we should verify calldata[0:4] against the function selector of initNexus

K1ValidatorFactory
// Review: if salt should include K1 Validator address as well

2024-05-24 16:31 UTC, livingrockrises commented on contracts/utils/Bootstrap.sol
> +        BootstrapConfig[] calldata $valdiators,
which typo?

2024-05-25 10:10 UTC, Aboudjem approved these changes

2024-05-26 12:58 UTC, merged