add hardhat deployment script
bcnmy/nexus pull request #97
Opened 2024-06-06 07:01 UTC by livingrockrises

2024-06-06 08:45 UTC, Aboudjem commented
I've made the change to the base branch to 'dev' we shouldn't push anything directly to 'main', This will help us maintain a linear commit history and keep our repo clean

Let's prioritize merging all changes first into 'dev' before releasing the new version as 'beta-1'

2024-06-06 10:09 UTC, Aboudjem approved these changes

2024-06-06 10:10 UTC, Aboudjem requested changes
please move the arguments.js to deployment(s) folder

2024-06-12 21:04 UTC, livingrockrises commented
> please move the arguments.js to deployment(s) folder

done

2024-06-13 09:39 UTC, Aboudjem approved these changes

2024-06-13 09:42 UTC, merged